# --- CONFIGURAÇÃO DO BANCO DE DADOS (RENDER) ---
spring.datasource.url=jdbc:postgresql://dpg-d61pdei4d50c73afikp0-a.oregon-postgres.render.com:5432/frota_db_a6sm
spring.datasource.username=frota_db_a6sm_user
spring.datasource.password=FcO3LN0z7stPtwFOxE7gAPt4rNBqIKhh
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURAÇÃO DO HIBERNATE ---
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- PREVENÇÃO DE ERROS ---
# Isso impede que o Spring tente rodar scripts de inicialização que podem buscar o H2
spring.sql.init.mode=never